name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Debug dist output
        run: |
          echo "===== FILES IN DIST ====="
          find dist -type f
          echo "===== INDEX.HTML CONTENT ====="
          cat dist/index.html
          echo "=============================="

          # Если в index.html есть /src/, прерываем деплой
          if grep -q "/src/" dist/index.html; then
            echo "ERROR: Found /src/ in built index.html — build is incorrect"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
